link : main.o utils.o vector.o
	gcc main.o utils.o vector.o -o vector.exe

main.o :
	gcc -c main.c

utils.o :
	gcc -c utils.c

vector.o :
	gcc -c vector.c

clear :
	rm -f utils.o vector.o main.o vector.exe
