link : main.o vector.o utils.o
	gcc main.o vector.o utils.o -o vector.exe 

main.o : 
	gcc -c main.c 

vector.o : 
	gcc -c vector.c

utils.o : 
	gcc -c utils.c

clear : 
	rm -f vector.o main.o utils.o vector.exe 

